<?php

namespace Database\Seeders;

use App\Models\BeritaArticle;
use App\Models\BeritaCategory;
use App\Models\BeritaPlacement;
use App\Models\BeritaStory;
use Illuminate\Database\Seeder;

/**
 * Memindahkan 28 berita, kategori, dan 3 Cerita Skaneda yang sebelumnya
 * hardcoded di halaman publik ke database. Foto memakai file yang sudah
 * ada di public/images/berita/ (tidak dipindah). Hanya mengisi tabel yang
 * masih kosong, jadi aman diulang dan tidak menimpa hasil edit admin.
 */
class BeritaSeeder extends Seeder
{
    public function run(): void
    {
        if (!BeritaCategory::query()->exists()) {
            foreach ([
                ['sekolah', 'Sekolah', 'sekolah', 'fa-school'],
                ['siswa', 'Siswa', 'siswa', 'fa-user-graduate'],
                ['prestasi', 'Prestasi', 'prestasi', 'fa-trophy'],
                ['kegiatan', 'Kegiatan', 'kegiatan', 'fa-flag'],
                ['akademik', 'Akademik', 'akademik', 'fa-book-open'],
                ['ekstrakurikuler', 'Ekstrakurikuler', 'ekstrakurikuler', 'fa-users'],
                ['humas', 'Humas', 'humas', 'fa-handshake'],
            ] as $i => [$key, $label, $color, $icon]) {
                BeritaCategory::create(['key' => $key, 'label' => $label, 'color' => $color, 'icon' => $icon, 'order' => $i]);
            }
        }

        if (BeritaArticle::query()->exists()) {
            return;
        }

        $rows = [
            // [judul, kategori, label tanggal, foto, excerpt, isi (array paragraf)]
            ['Uji Kompetensi Keahlian (UKK) Jurusan APHP', 'kegiatan', null, 'images/berita/ukk-aphp.jpeg', 'Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Agribisnis Pengolahan Hasil Pertanian (APHP) dengan melakukan praktik pembuatan produk roti.', ['Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Agribisnis Pengolahan Hasil Pertanian (APHP) dengan melakukan praktik pembuatan produk roti. Kegiatan dimulai dari menyiapkan dan menimbang bahan sesuai takaran, mencampurkan bahan hingga menjadi adonan, melakukan proses pengulenan dan fermentasi, kemudian membentuk adonan sesuai ukuran. Setelah itu, adonan dipanggang hingga matang, kemudian dilakukan pengecekan hasil dan pengemasan produk roti agar siap disajikan.']],
            ['Uji Kompetensi Keahlian (UKK) Jurusan DKV', 'kegiatan', null, 'images/berita/ukk-dkv.jpeg', 'Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Desain Komunikasi Visual (DKV) dengan membuat dan menampilkan cosplay berdasarkan karakter yang disukai.', ['Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Desain Komunikasi Visual (DKV) dengan membuat dan menampilkan cosplay berdasarkan karakter yang disukai. Selain itu, kegiatan juga meliputi pembuatan desain flyer sebagai media visual untuk memperkenalkan karakter atau konsep yang dipilih. Setelah desain selesai, hasil flyer dan konsep cosplay dipresentasikan di depan untuk menjelaskan ide, proses pembuatan, serta konsep desain yang digunakan.']],
            ['Uji Kompetensi Keahlian (UKK) Jurusan Kuliner', 'kegiatan', null, 'images/berita/ukk-kuliner.jpeg', 'Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Kuliner dengan melakukan praktik pengolahan dan penyajian makanan.', ['Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Kuliner dengan melakukan praktik pengolahan dan penyajian makanan. Kegiatan tidak hanya mencakup proses persiapan bahan dan pembuatan makanan, tetapi juga penataan hidangan agar terlihat menarik dan sesuai standar penyajian. Setelah makanan siap, peserta melakukan pelayanan kepada tamu seperti pada pelayanan di hotel, mulai dari menyiapkan meja, menyajikan hidangan, hingga memberikan pelayanan dengan sikap yang ramah dan profesional.']],
            ['Uji Kompetensi Keahlian (UKK) Jurusan LPS', 'kegiatan', null, 'images/berita/ukk-lps.jpeg', 'Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Layanan Perbankan Syariah (LPS) dengan melakukan praktik yang berkaitan dengan pelayanan di bidang perbankan.', ['Melaksanakan kegiatan Uji Kompetensi Keahlian (UKK) pada jurusan Layanan Perbankan Syariah (LPS) dengan melakukan praktik yang berkaitan dengan pelayanan di bidang perbankan. Kegiatan meliputi persiapan dan penyampaian informasi kepada nasabah serta praktik komunikasi dan pelayanan secara langsung. Peserta juga mempresentasikan hasil atau materi yang telah dipersiapkan di depan penguji sebagai bagian dari penilaian kompetensi, dengan memperhatikan sikap, komunikasi, ketelitian, dan profesionalitas dalam memberikan pelayanan.']],
            ['Sukses! Rekayasa Perangkat Lunak (RPL) SMK Negeri 2 Mojokerto Laksanakan Uji Kompetensi Keahlian', 'kegiatan', null, 'images/berita/ukk-rpl.jpeg', 'Kegiatan Uji Kompetensi Kelulusan Kompetensi Keahlian Rekayasa Perangkat Lunak (RPL) dilaksanakan pada 18–20 Februari 2025 dan diikuti oleh siswa kelas XII RPL SMK Negeri 2 Mojokerto.', ['Kegiatan Uji Kompetensi Kelulusan Kompetensi Keahlian Rekayasa Perangkat Lunak (RPL) dilaksanakan pada 18–20 Februari 2025 dan diikuti oleh siswa kelas XII RPL SMK Negeri 2 Mojokerto. Kegiatan ini bertujuan untuk mengukur kemampuan dan pencapaian kompetensi siswa sesuai dengan bidang keahlian yang dipelajari.', 'Pelaksanaan ujian bekerja sama dengan PT Otak Kanan Surabaya dan Khofie Soft dengan melibatkan dewan penguji dari dunia industri serta alumni RPL. Dalam ujian ini, siswa mengerjakan project pembuatan aplikasi berbasis web menggunakan Laravel, seperti aplikasi toko online, perpustakaan digital, dan aplikasi kasir.', 'Melalui kegiatan ini, siswa diharapkan mampu menerapkan keterampilan pemrograman yang telah dipelajari sekaligus mempersiapkan diri untuk menghadapi dunia kerja dan industri. Kegiatan ini juga menjadi kesempatan bagi siswa untuk mengukur dan mengembangkan kemampuan dalam pembuatan aplikasi berbasis web maupun mobile.']],
            ['P5: Praktik Simulasi Pernikahan', 'kegiatan', 'Projek P5', 'images/berita/nikah.jpeg', 'Melaksanakan kegiatan Projek Penguatan Profil Pelajar Pancasila (P5) melalui praktik simulasi pernikahan yang dilakukan oleh siswa kelas XI.', ['Melaksanakan kegiatan Projek Penguatan Profil Pelajar Pancasila (P5) melalui praktik simulasi pernikahan yang dilakukan oleh siswa kelas XI. Kegiatan ini merupakan penerapan dari materi pembelajaran tentang pernikahan yang telah dipelajari di kelas. Dalam praktiknya, siswa melakukan simulasi rangkaian prosesi pernikahan dengan pembagian peran sesuai tugas masing-masing. Kegiatan ini bertujuan untuk memberikan pengalaman secara langsung serta meningkatkan pemahaman siswa mengenai proses dan ketentuan dalam pernikahan.']],
            ['Paduan Suara Skaneda', 'kegiatan', null, 'images/berita/padus.jpeg', 'Melaksanakan kegiatan paduan suara yang diikuti oleh seluruh angkatan sebagai bagian dari kegiatan sekolah.', ['Melaksanakan kegiatan paduan suara yang diikuti oleh seluruh angkatan sebagai bagian dari kegiatan sekolah. Setiap kelas mengirimkan empat perwakilan yang terdiri dari dua siswa laki-laki dan dua siswa perempuan. Para peserta berlatih bersama untuk menyatukan suara, menjaga kekompakan, serta mempersiapkan penampilan paduan suara. Kegiatan ini bertujuan untuk meningkatkan kerja sama, kedisiplinan, dan rasa percaya diri siswa dalam bernyanyi secara berkelompok.']],
            ['SMKN 2 Mojokerto Jadi Tuan Rumah Pelatihan Pembelajaran Mendalam Batch 2 untuk Meningkatkan Kompetensi Guru', 'akademik', '11–16 Agustus 2025', 'images/berita/tuan-rumah.jpeg', 'Kegiatan Pelatihan Pembelajaran Mendalam bagi Guru Jenjang SMK Batch 2 dilaksanakan selama enam hari, mulai tanggal 11 hingga 16 Agustus 2025, bertempat di Aula SMK Negeri 2 Mojokerto.', ['Kegiatan Pelatihan Pembelajaran Mendalam bagi Guru Jenjang SMK Batch 2 dilaksanakan selama enam hari, mulai tanggal 11 hingga 16 Agustus 2025, bertempat di Aula SMK Negeri 2 Mojokerto. Kegiatan ini diikuti oleh 25 guru, yang terdiri dari 12 guru dari Kabupaten Mojokerto dan 13 guru dari Kota Mojokerto, serta dibuka secara resmi oleh Bapak Mudianto, S.Pd., M.M.', 'Pelatihan ini bertujuan untuk meningkatkan pemahaman dan kompetensi guru mengenai pembelajaran mendalam sehingga nantinya dapat menjadi fasilitator dan menyebarluaskan ilmu yang diperoleh ke sekolah masing-masing maupun sekolah lainnya. Dalam kegiatan tersebut, guru mendapatkan pembekalan mengenai perencanaan, pelaksanaan, dan evaluasi pembelajaran, serta pentingnya meningkatkan potensi dan profesionalitas sebagai seorang pendidik.', 'Kegiatan ini mendapat dukungan dari pihak SMK Negeri 2 Mojokerto, termasuk kepala sekolah, wakil kepala sekolah bidang kurikulum, dewan guru, staf, dan karyawan. Melalui pelatihan ini, diharapkan para guru dapat bersinergi dan menerapkan pembelajaran mendalam secara lebih baik dalam proses pembelajaran di sekolah.']],
            ['Sosialisasi Genre Goes To School Ciptakan Harmonisasi di Kalangan Siswa di SMK Negeri 2 Mojokerto', 'kegiatan', '6 Agustus 2025', 'images/berita/genre.jpeg', 'Kegiatan Sosialisasi Genre Goes To School dilaksanakan di Aula SMK Negeri 2 Mojokerto pada Rabu, 6 Agustus 2025.', ['Kegiatan Sosialisasi Genre Goes To School dilaksanakan di Aula SMK Negeri 2 Mojokerto pada Rabu, 6 Agustus 2025. Kegiatan ini diselenggarakan oleh Dinas Kesehatan Kota Mojokerto melalui Duta Genre yang bekerja sama dengan ekstrakurikuler PIK-R dan diikuti oleh 40 siswa anggota PIK-R.', 'Kegiatan ini bertujuan untuk meningkatkan pemahaman dan peran anggota PIK-R sebagai konselor sebaya yang dapat menjadi teman serta tempat berbagi bagi siswa lainnya. Selain itu, kegiatan ini juga mendukung upaya SMK Negeri 2 Mojokerto dalam mewujudkan Sekolah Siaga Kependudukan. Melalui sosialisasi ini, siswa diharapkan mampu memberikan motivasi, dukungan, dan informasi yang bermanfaat bagi teman sebaya.']],
            ['SMK Negeri 2 Mojokerto Sukses Laksanakan Rekrutmen Pramuniaga Toko Emas Wahyu Redjo', 'sekolah', '23 Juli 2025', 'images/berita/wahyu-redjo.jpeg', 'Kegiatan Rekrutmen Pramuniaga Toko Emas Wahyu Redjo dilaksanakan bekerja sama dengan BKK SMK Negeri 2 Mojokerto pada Rabu, 23 Juli 2025.', ['Kegiatan Rekrutmen Pramuniaga Toko Emas Wahyu Redjo dilaksanakan bekerja sama dengan BKK SMK Negeri 2 Mojokerto pada Rabu, 23 Juli 2025. Kegiatan ini diikuti oleh 131 siswa kelas XII dan bertempat di Lab RPL SMK Negeri 2 Mojokerto.', 'Kegiatan rekrutmen ini bertujuan untuk memberikan kesempatan kepada lulusan SMK Negeri 2 Mojokerto agar dapat memperoleh pekerjaan sesuai dengan kualifikasi dan kompetensi yang dimiliki. Melalui kegiatan ini, peserta mengikuti proses seleksi untuk mendapatkan kesempatan bekerja sebagai pramuniaga di Toko Emas Wahyu Redjo.', 'Kegiatan ini mendapat dukungan dari pihak sekolah dan BKK SMK Negeri 2 Mojokerto. Diharapkan melalui kegiatan rekrutmen seperti ini, semakin banyak lulusan yang dapat langsung memasuki dunia kerja setelah menyelesaikan pendidikan serta memiliki pengalaman dalam mengikuti proses seleksi kerja.']],
            ['LPS SMKN 2 Mojokerto Gelar Literasi Keuangan Bersama FIF Group', 'akademik', '24 Juli 2025', 'images/berita/literasikeuangan.jpeg', 'Kegiatan Literasi Keuangan dan Edukasi Pembiayaan bersama FIF Group dilaksanakan oleh jurusan Layanan Perbankan Syariah (LPS) SMK Negeri 2 Mojokerto pada Kamis, 24 Juli 2025, di Aula SMK Negeri 2 Mojokerto.', ['Kegiatan Literasi Keuangan dan Edukasi Pembiayaan bersama FIF Group dilaksanakan oleh jurusan Layanan Perbankan Syariah (LPS) SMK Negeri 2 Mojokerto pada Kamis, 24 Juli 2025, di Aula SMK Negeri 2 Mojokerto. Kegiatan ini diikuti oleh 72 siswa kelas XI LPS 1 dan XI LPS 2.', 'Kegiatan ini bertujuan untuk meningkatkan pemahaman siswa mengenai literasi keuangan, konsep pembiayaan, serta Industri Keuangan Non Bank (IKNB) melalui kerja sama dengan DUDI FIF Group Mojokerto. Selain memperoleh materi dari praktisi, siswa juga mendapatkan wawasan tentang dunia kerja dan peluang pengembangan kompetensi di bidang perbankan syariah. Diharapkan kegiatan ini dapat memperkuat kerja sama antara sekolah dan dunia industri serta mempersiapkan siswa menghadapi dunia kerja maupun kewirausahaan.']],
            ['RPL SMKN 2 Mojokerto Gelar Pelatihan Web dengan Framework Laravel 2024', 'akademik', 'September 2024', 'images/berita/pelatihan-web.jpeg', 'Kegiatan Pelatihan Web dengan Framework Laravel dilaksanakan pada September 2024 dan diikuti oleh 37 perwakilan siswa kelas XII SMK Negeri 2 Mojokerto.', ['Kegiatan Pelatihan Web dengan Framework Laravel dilaksanakan pada September 2024 dan diikuti oleh 37 perwakilan siswa kelas XII SMK Negeri 2 Mojokerto. Pelatihan ini bertujuan untuk meningkatkan kompetensi siswa di bidang pengembangan perangkat lunak, khususnya penggunaan framework Laravel sebagai persiapan menghadapi UKK dan dunia kerja.', 'Kegiatan dibimbing langsung oleh guru tamu yang merupakan alumni SMK Negeri 2 Mojokerto, yaitu Khafid Ilham dan Bachtiar Affandy. Melalui pelatihan ini, siswa mendapatkan pengalaman dan pengetahuan tambahan dalam coding serta pengerjaan proyek menggunakan Laravel sehingga dapat lebih siap dalam menghadapi UKK dan mengembangkan keterampilan di bidang pemrograman.']],
            ['Istimewa! SMKN 2 Mojokerto Berhasil Menggelar Pemilihan Ketua OSIS Periode 2024–2025', 'sekolah', '19 September 2024', 'images/berita/pemilos.jpeg', 'Kegiatan Pemilihan Ketua OSIS Periode 2024–2025 dilaksanakan pada 19 September 2024 dan diikuti oleh 1.216 siswa SMK Negeri 2 Mojokerto.', ['Kegiatan Pemilihan Ketua OSIS Periode 2024–2025 dilaksanakan pada 19 September 2024 dan diikuti oleh 1.216 siswa SMK Negeri 2 Mojokerto. Kegiatan ini merupakan agenda rutin sekolah yang bertujuan untuk memberikan kesempatan kepada siswa dalam memilih pemimpin serta menjadi bagian dari proses kaderisasi kepemimpinan di lingkungan sekolah.', 'Dalam pemilihan tersebut, terdapat tiga pasangan calon yang menyampaikan visi dan misi sebelum proses pencoblosan. Berdasarkan hasil penghitungan suara, Paslon 2, yaitu Lola Devia dan Carla Nur, memperoleh suara terbanyak dengan 481 suara. Kegiatan ini didukung oleh pihak sekolah, dewan guru, dan Pembina OSIS serta dilaksanakan dengan mengedepankan kekompakan, solidaritas, dan integritas.']],
            ['Skaneda Kawi Laras (Kamis Wiwitan Laku Adab Lan Rasa Sayekti)', 'sekolah', 'Program budaya', 'images/berita/kawi-laras.jpeg', 'Program Kawi Laras (Kamis Wiwitan Laku Adab Lan Rasa Sayekti) merupakan program budaya yang dilaksanakan SMKN 2 Mojokerto setiap minggu kedua dalam satu bulan.', ['Program Kawi Laras (Kamis Wiwitan Laku Adab Lan Rasa Sayekti) merupakan program budaya yang dilaksanakan SMKN 2 Mojokerto setiap minggu kedua dalam satu bulan. Kegiatan ini mengajak seluruh siswa, guru, dan karyawan untuk mengenakan pakaian tradisional Jawa seperti lurik dan kebaya serta menerapkan nilai-nilai budaya Jawa dalam kehidupan sehari-hari.', 'Program ini bertujuan untuk melestarikan budaya dan mengenalkan kembali nilai unggah-ungguh, sopan santun, rasa hormat, serta tepa selira kepada siswa. Kegiatan Kawi Laras mendapat dukungan dari seluruh keluarga besar SMKN 2 Mojokerto dan diharapkan dapat membentuk siswa yang berkarakter, santun, serta tetap menghargai budaya Jawa.']],
            ['Sukses! SMK Negeri 2 Mojokerto Laksanakan Survei Lingkungan Belajar', 'akademik', '19 September 2024', 'images/berita/survei-lb.jpeg', 'Kegiatan Survei Lingkungan Belajar (Sulingjar) dilaksanakan pada 19 September 2024 dan diikuti oleh seluruh guru SMK Negeri 2 Mojokerto.', ['Kegiatan Survei Lingkungan Belajar (Sulingjar) dilaksanakan pada 19 September 2024 dan diikuti oleh seluruh guru SMK Negeri 2 Mojokerto. Sulingjar merupakan survei yang digunakan untuk mengevaluasi dan memetakan berbagai aspek yang mendukung kualitas pembelajaran di lingkungan sekolah.', 'Melalui kegiatan ini, sekolah dapat mengetahui kondisi lingkungan belajar, kualitas pembelajaran, serta faktor-faktor yang dapat memengaruhi hasil belajar siswa. Sulingjar juga mencakup aspek keamanan, kebinekaan, kesetaraan, inklusivitas, kepemimpinan sekolah, serta dukungan orang tua dan siswa. Kegiatan ini diharapkan dapat membantu menciptakan lingkungan belajar yang aman, nyaman, dan menyenangkan.']],
            ['P5: Bazar Makanan Tradisional', 'kegiatan', 'Projek P5', 'images/berita/bazar.jpeg', 'Melaksanakan kegiatan Projek Penguatan Profil Pelajar Pancasila (P5) melalui kegiatan bazar makanan tradisional.', ['Melaksanakan kegiatan Projek Penguatan Profil Pelajar Pancasila (P5) melalui kegiatan bazar makanan tradisional. Setiap jurusan dan seluruh angkatan bekerja sama dalam satu stan bazar dengan menjual berbagai macam makanan tradisional. Kegiatan ini meliputi persiapan produk, penataan stan, pelayanan kepada pembeli, hingga proses penjualan. Melalui kegiatan ini, siswa dapat belajar bekerja sama, berkomunikasi, mengelola penjualan, serta meningkatkan kreativitas dan jiwa kewirausahaan.']],
            ['Tes Kebugaran Sehat: Program Unggulan Gerakan Sekolah Sehat SMK Negeri 2 Mojokerto', 'kegiatan', '21 Agustus 2024', 'images/berita/tes-kebugaran.jpeg', 'Kegiatan Tes Kebugaran sebagai bagian dari Program Gerakan Sekolah Sehat dilaksanakan pada 21 Agustus 2024 di SMK Negeri 2 Mojokerto.', ['Kegiatan Tes Kebugaran sebagai bagian dari Program Gerakan Sekolah Sehat dilaksanakan pada 21 Agustus 2024 di SMK Negeri 2 Mojokerto. Kegiatan ini diawali dengan pengambilan sampel 30 siswa dari berbagai jurusan, terdiri dari 15 siswa laki-laki dan 15 siswa perempuan.', 'Tes ini bertujuan untuk memetakan tingkat kebugaran siswa dan mengetahui kondisi kebugaran fisik mereka. Beberapa tes yang dilakukan meliputi Hand Eye Coordination Test, Standing Broad Jump Test, Dipping Test, T-Test, dan Bleep Test. Kegiatan ini diharapkan dapat dilaksanakan secara rutin agar sekolah dapat memantau dan meningkatkan tingkat kebugaran siswa.']],
            ['SMK Negeri 2 Mojokerto: Sekolah Pioneer, Gerakan Sekolah Sehat 2024', 'kegiatan', '2024', 'images/berita/sekolah-pioneer.jpeg', 'SMK Negeri 2 Mojokerto ditunjuk sebagai perwakilan Kota Mojokerto dalam Program Gerakan Sekolah Sehat yang dicanangkan oleh pemerintah melalui Dinas Pendidikan Provinsi Jawa Timur.', ['SMK Negeri 2 Mojokerto ditunjuk sebagai perwakilan Kota Mojokerto dalam Program Gerakan Sekolah Sehat yang dicanangkan oleh pemerintah melalui Dinas Pendidikan Provinsi Jawa Timur. Program ini bertujuan untuk membudayakan pola hidup sehat bagi seluruh warga sekolah, meliputi kesehatan fisik, kesehatan jiwa, kesehatan lingkungan, dan imunisasi.', 'Pelaksanaan program melibatkan seluruh warga sekolah serta bekerja sama dengan pihak luar seperti Puskesmas dan BKKBN. Berbagai kegiatan yang telah dilakukan antara lain sosialisasi gizi seimbang, membawa bekal sehat, penyediaan air minum, senam bersama, dan tes kebugaran siswa. Melalui program ini, diharapkan tercipta lingkungan sekolah yang sehat, nyaman, dan mendukung proses pembelajaran.']],
            ['Sukses! SMKN 2 Mojokerto Berhasil Laksanakan Tes Asesmen Nasional Berbasis Komputer 2024', 'akademik', '21–22 Agustus 2024', 'images/berita/anbk.jpeg', 'Kegiatan Asesmen Nasional Berbasis Komputer (ANBK) dilaksanakan pada 21–22 Agustus 2024 di Lab RPL SMK Negeri 2 Mojokerto.', ['Kegiatan Asesmen Nasional Berbasis Komputer (ANBK) dilaksanakan pada 21–22 Agustus 2024 di Lab RPL SMK Negeri 2 Mojokerto. Kegiatan ini diikuti oleh 50 siswa perwakilan dari berbagai jurusan, terdiri dari 45 siswa utama dan 5 siswa cadangan.', 'ANBK merupakan program evaluasi pendidikan yang bertujuan untuk mengetahui dan meningkatkan mutu pembelajaran di sekolah. Asesmen ini mencakup Literasi dan Numerasi, Survei Karakter, serta Survei Lingkungan Belajar.', 'Untuk mempersiapkan siswa, sekolah memberikan bimbingan dan latihan secara intensif selama beberapa minggu dengan melibatkan wali kelas dan guru terkait. Melalui kegiatan ini, diharapkan siswa dapat mengikuti asesmen dengan baik dan memperoleh hasil yang mendukung peningkatan kualitas pendidikan serta Rapor Pendidikan SMK Negeri 2 Mojokerto.']],
            ['Khidmat! SMK Negeri 2 Mojokerto Peringati Hari Pramuka Ke-63 Tahun 2024', 'kegiatan', '14 Agustus 2024', 'images/berita/haripramuka.jpeg', 'Kegiatan Peringatan Hari Pramuka ke-63 dilaksanakan pada 14 Agustus 2024 dan diikuti oleh seluruh siswa kelas X, XI, dan XII SMK Negeri 2 Mojokerto.', ['Kegiatan Peringatan Hari Pramuka ke-63 dilaksanakan pada 14 Agustus 2024 dan diikuti oleh seluruh siswa kelas X, XI, dan XII SMK Negeri 2 Mojokerto. Kegiatan berupa upacara dengan tema “Pramuka Berjiwa Pancasila, Menjaga NKRI” yang dipimpin oleh Kepala SMK Negeri 2 Mojokerto, Bapak Drs. Akhmad Mukhlason.', 'Dalam amanatnya, disampaikan pentingnya menjaga persatuan, mencintai bangsa dan negara, melestarikan budaya Indonesia, serta menerapkan nilai-nilai Dasa Dharma Pramuka dalam kehidupan sehari-hari. Seluruh warga sekolah juga mengenakan seragam Pramuka lengkap sebagai bentuk kedisiplinan dan keteladanan sesuai dengan nilai “Disiplin dan Berprestasi” yang menjadi ikon SMK Negeri 2 Mojokerto.']],
            ['Istighosah Akbar, Program Unggulan Keagamaan di SMK Negeri 2 Mojokerto', 'kegiatan', '9 Agustus 2024', 'images/berita/istighosah.jpeg', 'Kegiatan Istighosah Akbar dilaksanakan pada Jumat, 9 Agustus 2024 dan diikuti oleh seluruh siswa kelas X, XI, dan XII SMK Negeri 2 Mojokerto.', ['Kegiatan Istighosah Akbar dilaksanakan pada Jumat, 9 Agustus 2024 dan diikuti oleh seluruh siswa kelas X, XI, dan XII SMK Negeri 2 Mojokerto. Kegiatan ini merupakan salah satu program unggulan keagamaan sekolah yang bertujuan untuk meningkatkan keimanan serta membentuk sikap spiritual dan karakter siswa.', 'Acara diawali dengan pembacaan Ratibul Hadad, dilanjutkan Mahalul Qiyam, Istighosah, tausiyah, dan doa bersama. Kegiatan ini juga diisi dengan program Jumat Curhat bersama Polsek Prajuritkulon yang memberikan edukasi mengenai keselamatan dan kepatuhan terhadap peraturan lalu lintas. Melalui kegiatan ini, diharapkan siswa dapat meningkatkan ketakwaan, kedisiplinan, serta menerapkan nilai-nilai kebaikan dalam kehidupan sehari-hari.']],
            ['SMKN 2 Mojokerto Gelar Kerjasama dengan Program Bakti BCA yang Didukung oleh OJK', 'akademik', '8 Agustus 2024', 'images/berita/bakti-bca.jpeg', 'Kegiatan Program Bakti BCA dilaksanakan pada 8 Agustus 2024 di Aula SMK Negeri 2 Mojokerto dan diikuti oleh siswa kelas XII Layanan Perbankan Syariah (LPS).', ['Kegiatan Program Bakti BCA dilaksanakan pada 8 Agustus 2024 di Aula SMK Negeri 2 Mojokerto dan diikuti oleh siswa kelas XII Layanan Perbankan Syariah (LPS). Kegiatan ini merupakan kerja sama SMK Negeri 2 Mojokerto dengan Bank Central Asia (BCA) yang didukung oleh Otoritas Jasa Keuangan (OJK) dalam memberikan edukasi dan literasi keuangan kepada siswa.', 'Melalui kegiatan ini, siswa mendapatkan wawasan mengenai dunia perbankan, produk perbankan, perkembangan industri keuangan, serta pentingnya literasi keuangan. Selain itu, Program Bakti BCA juga memberikan informasi mengenai kesempatan beasiswa bagi siswa SMK berprestasi. Kegiatan ini diharapkan dapat menambah pengetahuan dan keterampilan siswa sebagai bekal untuk melanjutkan pendidikan maupun menghadapi dunia kerja.']],
            ['Sukses! SMKN 2 Mojokerto Berhasil Menggelar Tes TOEIC 2024', 'akademik', '7 Agustus 2024', 'images/berita/tes-toeic.jpeg', 'Kegiatan Tes TOEIC 2024 dilaksanakan pada 7 Agustus 2024 di Lab DKV SMK Negeri 2 Mojokerto dan diikuti oleh 24 siswa perwakilan dari berbagai jurusan.', ['Kegiatan Tes TOEIC 2024 dilaksanakan pada 7 Agustus 2024 di Lab DKV SMK Negeri 2 Mojokerto dan diikuti oleh 24 siswa perwakilan dari berbagai jurusan. Tes TOEIC merupakan agenda rutin sekolah yang bertujuan untuk mengukur kemampuan Bahasa Inggris siswa dalam konteks dunia kerja melalui sertifikasi berstandar internasional.', 'Pelaksanaan tes merupakan kerja sama antara Kemendikbud dan International Test Center (ITC). Melalui kegiatan ini, siswa diharapkan dapat meningkatkan kemampuan Bahasa Inggris serta mempersiapkan diri untuk melanjutkan pendidikan maupun memasuki dunia kerja. Siswa juga didorong untuk berlatih secara disiplin dan meningkatkan motivasi agar memperoleh hasil yang maksimal.']],
            ['Treasury Goes To School SMK Negeri 2 Mojokerto Dua Dekade Indonesian Treasury, Terus Berinovasi Melayani Negeri', 'akademik', '25 Juli 2024', 'images/berita/treasury.jpeg', 'Kegiatan Treasury Goes To School dilaksanakan pada 25 Juli 2024 di Aula SMK Negeri 2 Mojokerto dan diikuti oleh siswa jurusan Layanan Perbankan Syariah (LPS).', ['Kegiatan Treasury Goes To School dilaksanakan pada 25 Juli 2024 di Aula SMK Negeri 2 Mojokerto dan diikuti oleh siswa jurusan Layanan Perbankan Syariah (LPS). Kegiatan ini merupakan kerja sama antara Kantor Pelayanan Perbendaharaan Negara (KPPN) Mojokerto dengan SMK Negeri 2 Mojokerto dalam rangka memperingati Hari Bakti Perbendaharaan.', 'Kegiatan ini bertujuan untuk menambah wawasan siswa mengenai APBN, tugas dan pengelolaan KPPN, serta pentingnya menghindari gratifikasi. Antusiasme siswa terlihat dari sesi tanya jawab yang berlangsung aktif. Kegiatan ditutup dengan pemberian apresiasi dari KPPN Mojokerto sebagai bentuk penghargaan atas kerja sama yang telah terjalin dengan SMK Negeri 2 Mojokerto.']],
            ['LDKPD SMKN 2 Mojokerto: Membangun Jiwa Kepemimpinan dan Kesiapan Pengurus OSIS', 'kegiatan', '13–14 Oktober 2023', 'images/berita/ldkpd.jpeg', 'Kegiatan Latihan Dasar Kepemimpinan Peserta Didik (LDKPD) dilaksanakan pada 13–14 Oktober 2023 di Royal Hotel Trawas Mojokerto dan diikuti oleh sekitar 65 peserta.', ['Kegiatan Latihan Dasar Kepemimpinan Peserta Didik (LDKPD) dilaksanakan pada 13–14 Oktober 2023 di Royal Hotel Trawas Mojokerto dan diikuti oleh sekitar 65 peserta. Kegiatan ini merupakan pelatihan dasar kepemimpinan bagi calon pengurus OSIS periode 2023–2024 sebagai bekal dalam menjalankan organisasi dan menjadi pemimpin yang bertanggung jawab.', 'Dalam kegiatan ini, peserta mendapatkan berbagai materi dan pengalaman mengenai dasar-dasar kepemimpinan, teknik komunikasi, kewirausahaan, penyusunan program kerja, kerja sama tim, serta kegiatan pengembangan diri melalui games dan pentas ekstrakurikuler. Melalui LDKPD, peserta diharapkan mampu meningkatkan kemampuan kepemimpinan, membangun kerja sama, serta memiliki mental dan karakter yang baik dalam menjalankan tugas sebagai pengurus OSIS.']],
            ['Pentingnya Kegiatan Kunjungan Industri bagi Siswa SMK', 'kegiatan', '13 Desember 2022', 'images/berita/KI.jpeg', 'Kegiatan Kunjungan Industri (KI) dilaksanakan oleh siswa kelas X RPL SMK Negeri 2 Mojokerto pada 13 Desember 2022 di Maspion IT.', ['Kegiatan Kunjungan Industri (KI) dilaksanakan oleh siswa kelas X RPL SMK Negeri 2 Mojokerto pada 13 Desember 2022 di Maspion IT. Kegiatan ini diikuti oleh 100 siswa dari kelas X RPL 1, X RPL 2, dan X RPL 3 sebagai bentuk pembelajaran di luar sekolah untuk mengenal dunia industri secara langsung.', 'Dalam kunjungan ini, siswa mendapatkan materi mengenai dunia software dan perkembangan teknologi informasi dari pihak Maspion IT. Selain itu, siswa juga diperkenalkan dengan Maspion Group dan diajak melihat berbagai produk elektronik yang tersedia di Maspion Square.', 'Melalui kegiatan ini, siswa diharapkan dapat menambah wawasan tentang dunia industri, memahami perkembangan teknologi, serta meningkatkan kompetensi, kedisiplinan, sikap, dan kesiapan menghadapi dunia kerja.']],
            ['BKK SMKN 2 Mojokerto Berinovasi Adakan Kegiatan Temu Alumni untuk Siswa Baru', 'sekolah', null, 'images/berita/temu-alumni.jpeg', 'Data isi artikel tidak tercantum pada dokumen Word yang tersedia.', ['Kegiatan Temu Alumni diselenggarakan oleh BKK SMK Negeri 2 Mojokerto sebagai upaya memberikan motivasi dan gambaran mengenai dunia kerja serta perguruan tinggi kepada siswa baru tahun pelajaran 2022–2023. Kegiatan ini menghadirkan alumni yang bekerja atau melanjutkan pendidikan sesuai dengan jurusan masing-masing.', 'Dalam kegiatan ini, alumni berbagi pengalaman, tips, saran, dan informasi mengenai peluang setelah lulus SMK. Siswa juga diberikan kesempatan untuk berdiskusi dan bertanya secara langsung mengenai dunia kerja, perkuliahan, maupun persiapan PKL. Melalui kegiatan ini, diharapkan siswa semakin termotivasi untuk mengembangkan keterampilan sesuai jurusannya serta memiliki gambaran dan persiapan untuk masa depan.']],
            ['BKK SMKN 2 Mojokerto Bekerjasama dengan PT.SAI Selenggarakan Rekrutmen Lulusan SMK', 'sekolah', null, 'images/berita/pt-sai.jpeg', 'BKK SMKN 2 Mojokerto bekerja sama dengan PT. Surabaya Autocomp Indonesia (PT. SAI) dalam kegiatan rekrutmen lulusan SMK yang dilaksanakan di Aula SMKN 2 Mojokerto.', ['BKK SMKN 2 Mojokerto bekerja sama dengan PT. Surabaya Autocomp Indonesia (PT. SAI) dalam kegiatan rekrutmen lulusan SMK yang dilaksanakan di Aula SMKN 2 Mojokerto. Kegiatan ini bertujuan membantu alumni memperoleh kesempatan kerja, khususnya sebagai operator produksi di bidang komponen otomotif Wiring Harness.', 'Rekrutmen diikuti oleh alumni SMKN 2 Mojokerto dan masyarakat umum. Proses seleksi meliputi administrasi, tes fisik, tes tulis, wawancara, hingga tes kesehatan. Kegiatan ini juga menjadi bentuk upaya BKK dalam memperluas kerja sama dengan dunia industri serta meningkatkan penyerapan lulusan SMK di dunia kerja.', 'Melalui kegiatan ini, BKK SMKN 2 Mojokerto berharap semakin banyak alumni yang mendapatkan kesempatan bekerja sesuai dengan kemampuan dan kualifikasinya.']],
            ['Sukses dan Kompeten! Kuliner SMK Negeri 2 Mojokerto Laksanakan Uji Kompetensi Keahlian', 'kegiatan', '17–21 Februari 2025', null, 'Kegiatan Uji Kompetensi Keahlian (UKK) Kuliner dilaksanakan pada 17–21 Februari 2025 dan diikuti oleh siswa kelas XII Kompetensi Keahlian Kuliner SMK Negeri 2 Mojokerto.', ['Kegiatan Uji Kompetensi Keahlian (UKK) Kuliner dilaksanakan pada 17–21 Februari 2025 dan diikuti oleh siswa kelas XII Kompetensi Keahlian Kuliner SMK Negeri 2 Mojokerto. Kegiatan ini bertujuan untuk menguji kemampuan siswa dalam bidang Pastry dan Cookery dengan melibatkan penguji dari Hotel Vasa Surabaya dan SHS Surabaya.', 'Materi yang diujikan meliputi pembuatan roti, choux paste, dan cake pada bidang Pastry, serta pembuatan masakan kontinental seperti appetizer, sandwich, soup, dan main course pada bidang Cookery. Melalui kegiatan ini, siswa dapat menerapkan keterampilan yang telah dipelajari, meningkatkan kepercayaan diri, serta mempersiapkan diri untuk menghadapi dunia kerja di bidang kuliner.']],
            ['Selamat dan Sukses! Desain Komunikasi Visual SMK Negeri 2 Mojokerto Laksanakan Uji Kompetensi Keahlian', 'kegiatan', '24–26 Februari 2025', null, 'Kegiatan Uji Kompetensi Keahlian (UKK) Desain Komunikasi Visual dilaksanakan pada 24–26 Februari 2025 dan diikuti oleh siswa kelas XII Kompetensi Keahlian DKV SMK Negeri 2 Mojokerto.', ['Kegiatan Uji Kompetensi Keahlian (UKK) Desain Komunikasi Visual dilaksanakan pada 24–26 Februari 2025 dan diikuti oleh siswa kelas XII Kompetensi Keahlian DKV SMK Negeri 2 Mojokerto. Kegiatan ini bertujuan untuk mengukur pencapaian kompetensi siswa setelah menyelesaikan pembelajaran sesuai bidang keahlian yang ditempuh.', 'Dalam UKK ini, siswa mengerjakan proyek rebranding potensi yang ada di Kota Mojokerto, seperti kuliner, fasilitas olahraga, wisata budaya, wisata religi, dan ruang terbuka hijau. Hasil karya yang dibuat meliputi logo, fotografi, poster, desain feed Instagram, serta video vlog atau reels. Melalui kegiatan ini, siswa dapat mengembangkan kreativitas dan kemampuan desain sebagai bekal untuk melanjutkan pendidikan, bekerja, maupun berwirausaha.']],
            ['Sukses! Layanan Perbankan Syariah (LPS) SMK Negeri 2 Mojokerto Laksanakan Uji Kompetensi Keahlian (UKK)', 'kegiatan', '18–20 Februari 2025', null, 'Kegiatan Uji Kompetensi Keahlian (UKK) Layanan Perbankan Syariah dilaksanakan pada 18–20 Februari 2025 dan diikuti oleh siswa kelas XII LPS SMK Negeri 2 Mojokerto.', ['Kegiatan Uji Kompetensi Keahlian (UKK) Layanan Perbankan Syariah dilaksanakan pada 18–20 Februari 2025 dan diikuti oleh siswa kelas XII LPS SMK Negeri 2 Mojokerto. Kegiatan ini bertujuan untuk mengukur dan meningkatkan kompetensi siswa dalam bidang layanan keuangan syariah dengan bekerja sama bersama BPD Jatim Cabang Jayanegara Kota Mojokerto.', 'Materi yang diujikan meliputi praktik dan teori layanan keuangan syariah, pembuatan laporan akuntansi manual syariah, serta praktik komputer syariah. Melalui kegiatan ini, siswa diharapkan mampu menerapkan kompetensi yang telah dipelajari, meningkatkan keterampilan, serta mempersiapkan diri untuk menghadapi dunia kerja dan bidang kewirausahaan.']],
            ['MAGANG/PRAKERIN SEMAKIN ASYIK BERSAMA JURUSAN PERBANKAN SYARIAH SKANEDA', 'akademik', 'Januari 2023', null, 'Kegiatan Magang/Prakerin merupakan program pembelajaran yang memberikan kesempatan kepada siswa untuk memperoleh pengalaman kerja secara langsung di Dunia Usaha/Dunia Industri (DU/DI).', ['Kegiatan Magang/Prakerin merupakan program pembelajaran yang memberikan kesempatan kepada siswa untuk memperoleh pengalaman kerja secara langsung di Dunia Usaha/Dunia Industri (DU/DI). Kegiatan ini dilaksanakan oleh siswa kelas XI selama enam bulan sebagai bentuk penerapan kompetensi yang telah dipelajari di sekolah.', 'Pada Januari 2023, siswa kelas XI Perbankan Syariah diberangkatkan ke berbagai instansi dan perusahaan mitra, seperti Bank Muamalat, Bank Syariah Indonesia, Bank Jatim, BPRS, KPPN, BAZNAS, dan beberapa instansi lainnya. Sebelum melaksanakan Prakerin, siswa dibekali keterampilan sesuai bidang keahlian, kemampuan beradaptasi, serta karakter dan etos kerja.', 'Melalui kegiatan Prakerin, siswa diharapkan dapat meningkatkan keterampilan, kedisiplinan, tanggung jawab, kepercayaan diri, serta memahami secara langsung dunia kerja sesuai dengan kompetensi yang dimiliki.']],
        ];

        $order = 0;
        $created = [];
        foreach ($rows as [$title, $cat, $dateLabel, $photo, $excerpt, $content]) {
            $article = BeritaArticle::create([
                'title'               => $title,
                'category_key'        => $cat,
                'date_label'          => $dateLabel,
                'excerpt'             => $excerpt,
                'content'             => implode("\n", $content),
                'photo'               => $photo,
                'show_in_initial_ten' => $order < 10,
                'order'               => $order++,
                'is_active'           => true,
            ]);
            $created[$title] = $article->id;
        }

        // Penempatan: featured besar + 4 berita samping (Berita Terkini), sesuai tampilan asli.
        BeritaPlacement::create(['slot' => 'featured', 'position' => 0, 'article_id' => $created['Uji Kompetensi Keahlian (UKK) Jurusan APHP']]);
        BeritaPlacement::create(['slot' => 'side', 'position' => 0, 'article_id' => $created['Uji Kompetensi Keahlian (UKK) Jurusan DKV']]);
        BeritaPlacement::create(['slot' => 'side', 'position' => 1, 'article_id' => $created['Uji Kompetensi Keahlian (UKK) Jurusan Kuliner']]);
        BeritaPlacement::create(['slot' => 'side', 'position' => 2, 'article_id' => $created['Uji Kompetensi Keahlian (UKK) Jurusan LPS']]);
        BeritaPlacement::create(['slot' => 'side', 'position' => 3, 'article_id' => $created['Sukses! Rekayasa Perangkat Lunak (RPL) SMK Negeri 2 Mojokerto Laksanakan Uji Kompetensi Keahlian']]);

        // Artikel Pilihan di sidebar.
        BeritaPlacement::create(['slot' => 'most_read', 'position' => 0, 'article_id' => $created['Istighosah Akbar, Program Unggulan Keagamaan di SMK Negeri 2 Mojokerto']]);
        BeritaPlacement::create(['slot' => 'most_read', 'position' => 1, 'article_id' => $created['SMKN 2 Mojokerto Gelar Kerjasama dengan Program Bakti BCA yang Didukung oleh OJK']]);
        BeritaPlacement::create(['slot' => 'most_read', 'position' => 2, 'article_id' => $created['LDKPD SMKN 2 Mojokerto: Membangun Jiwa Kepemimpinan dan Kesiapan Pengurus OSIS']]);
        BeritaPlacement::create(['slot' => 'most_read', 'position' => 3, 'article_id' => $created['MAGANG/PRAKERIN SEMAKIN ASYIK BERSAMA JURUSAN PERBANKAN SYARIAH SKANEDA']]);
        BeritaPlacement::create(['slot' => 'most_read', 'position' => 4, 'article_id' => $created['BKK SMKN 2 Mojokerto Bekerjasama dengan PT.SAI Selenggarakan Rekrutmen Lulusan SMK']]);

        // Cerita Skaneda (long-read feature).
        BeritaStory::create([
            'category_key' => 'prestasi',
            'title'        => 'Uji Kompetensi RPL: Mengasah Kompetensi untuk Dunia Industri',
            'teaser'       => 'UKK RPL menjadi ruang bagi siswa untuk menerapkan keterampilan pemrograman melalui proyek aplikasi berbasis web.',
            'content'      => implode("\n", ['Kegiatan ini bertujuan untuk mengukur kemampuan dan pencapaian kompetensi siswa sesuai dengan bidang keahlian yang dipelajari. Pelaksanaan ujian bekerja sama dengan PT Otak Kanan Surabaya dan Khofie Soft dengan melibatkan dewan penguji dari dunia industri serta alumni RPL. Dalam ujian ini, siswa mengerjakan project pembuatan aplikasi berbasis web menggunakan Laravel, seperti aplikasi toko online, perpustakaan digital, dan aplikasi kasir. Melalui kegiatan ini, siswa diharapkan mampu menerapkan keterampilan pemrograman yang telah dipelajari sekaligus mempersiapkan diri untuk menghadapi dunia kerja dan industri. Kegiatan ini juga menjadi kesempatan bagi siswa untuk mengukur dan mengembangkan kemampuan dalam pembuatan aplikasi berbasis web maupun mobile.']),
            'order'        => 0,
            'is_active'    => true,
        ]);
        BeritaStory::create([
            'category_key' => 'kegiatan',
            'title'        => 'Skaneda Kawi Laras: Menjaga Adab dan Rasa Sayekti',
            'teaser'       => 'Kawi Laras menjadi program budaya sekolah yang mengajak warga Skaneda mengenakan busana tradisional Jawa dan menerapkan nilai unggah-ungguh.',
            'content'      => implode("\n", ['Kegiatan ini mengajak seluruh siswa, guru, dan karyawan untuk mengenakan pakaian tradisional Jawa seperti lurik dan kebaya serta menerapkan nilai-nilai budaya Jawa dalam kehidupan sehari-hari. Program ini bertujuan untuk melestarikan budaya dan mengenalkan kembali nilai unggah-ungguh, sopan santun, rasa hormat, serta tepa selira kepada siswa. Kegiatan Kawi Laras mendapat dukungan dari seluruh keluarga besar SMKN 2 Mojokerto dan diharapkan dapat membentuk siswa yang berkarakter, santun, serta tetap menghargai budaya Jawa.']),
            'order'        => 1,
            'is_active'    => true,
        ]);
        BeritaStory::create([
            'category_key' => 'kegiatan',
            'title'        => 'Magang/Prakerin Perbankan Syariah: Belajar Langsung di Dunia Kerja',
            'teaser'       => 'Program Prakerin memberi kesempatan siswa Perbankan Syariah memperoleh pengalaman kerja langsung di berbagai instansi dan perusahaan mitra.',
            'content'      => implode("\n", ['Kegiatan ini dilaksanakan oleh siswa kelas XI selama enam bulan sebagai bentuk penerapan kompetensi yang telah dipelajari di sekolah. Pada Januari 2023, siswa kelas XI Perbankan Syariah diberangkatkan ke berbagai instansi dan perusahaan mitra, seperti Bank Muamalat, Bank Syariah Indonesia, Bank Jatim, BPRS, KPPN, BAZNAS, dan beberapa instansi lainnya. Sebelum melaksanakan Prakerin, siswa dibekali keterampilan sesuai bidang keahlian, kemampuan beradaptasi, serta karakter dan etos kerja. Melalui kegiatan Prakerin, siswa diharapkan dapat meningkatkan keterampilan, kedisiplinan, tanggung jawab, kepercayaan diri, serta memahami secara langsung dunia kerja sesuai dengan kompetensi yang dimiliki.']),
            'order'        => 2,
            'is_active'    => true,
        ]);
    }
}
