@extends('layouts.app')

@section('title', 'BKK & Loker — SMK Negeri 2 Mojokerto')
@section('description', 'Pusat informasi Bursa Kerja Khusus dan lowongan kerja SMK Negeri 2 Mojokerto untuk siswa dan alumni.')

@push('styles')
<style>
.bkk-page{background:#f7f9fc;color:#0d3a66;overflow:hidden;position:relative}.bkk-page *{box-sizing:border-box}
.bkk-hero{position:relative;min-height:clamp(520px,68vh,700px);display:flex;align-items:center;overflow:hidden;background:#fff;isolation:isolate}.bkk-hero:after{content:"BKK";position:absolute;z-index:0;right:-1%;bottom:-1%;font-family:var(--font-display);font-size:clamp(9rem,22vw,22rem);font-weight:900;line-height:.72;color:rgba(13,58,102,.035);-webkit-text-stroke:1px rgba(255,179,0,.08);pointer-events:none}
.bkk-orn{position:absolute;inset:0;pointer-events:none;overflow:hidden;z-index:1}.bkk-ring{position:absolute;width:330px;height:330px;border:1px solid rgba(13,58,102,.12);border-radius:50%;right:-80px;top:-100px}.bkk-ring:before{content:"";position:absolute;inset:32px;border:1px dashed rgba(255,179,0,.28);border-radius:50%}.bkk-dots{position:absolute;width:100px;height:100px;right:12%;bottom:12%;opacity:.45;background-image:radial-gradient(rgba(13,58,102,.35) 1.5px,transparent 1.6px);background-size:15px 15px}
.bkk-hero-inner{position:relative;z-index:3;width:100%;max-width:1240px;margin:0 auto;padding:clamp(4rem,9vw,7rem) clamp(1.25rem,5vw,5.5rem)}.bkk-kicker,.bkk-pill{display:inline-flex;align-items:center;gap:.5rem}.bkk-kicker{font-size:.72rem;font-weight:900;letter-spacing:.18em;text-transform:uppercase;color:#ff6f00;margin-bottom:1rem;padding:.55rem .85rem;border:1px solid rgba(255,111,0,.18);border-radius:999px;background:#fffaf5}.bkk-kicker:before{content:"";width:8px;height:8px;border-radius:50%;background:#ff6f00;box-shadow:0 0 0 6px rgba(255,111,0,.1)}
.bkk-title{font-family:var(--font-display);font-size:clamp(3.8rem,9vw,7.8rem);line-height:.88;letter-spacing:-.035em;margin:0;max-width:900px;text-transform:uppercase}.bkk-title .navy{display:block;color:#0d3a66}.bkk-title .gold{display:block;color:transparent;background:linear-gradient(135deg,#ffd54a,#ffb300 48%,#ff7a00);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}.bkk-lead{max-width:690px;margin:1.5rem 0 0;color:#52657a;font-size:1.08rem;line-height:1.85}.bkk-pills{display:flex;gap:.65rem;flex-wrap:wrap;margin-top:1.5rem}.bkk-pill{padding:.58rem .9rem;border-radius:999px;background:#fff;border:1px solid rgba(13,58,102,.12);box-shadow:0 8px 24px rgba(13,58,102,.06);font-size:.73rem;font-weight:800;color:#0d3a66}.bkk-pill i{color:#ffb300}
.bkk-strip{background:#0d3a66;color:#fff;border-bottom:3px solid #ffc107;overflow:hidden}.bkk-strip-inner{display:flex;align-items:center;gap:1rem;padding:.8rem clamp(1.25rem,5vw,5.5rem)}.bkk-strip-label{padding:.42rem .8rem;border-radius:999px;background:linear-gradient(135deg,#ffd54a,#ffb300);color:#0d3a66;font-size:.67rem;font-weight:900;letter-spacing:.14em;text-transform:uppercase;white-space:nowrap}.bkk-strip-text{font-size:.8rem;color:rgba(255,255,255,.86);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.bkk-section{position:relative;padding:clamp(4rem,8vw,7rem) clamp(1.25rem,5vw,5.5rem)}.bkk-container{max-width:1240px;margin:0 auto;position:relative;z-index:2}.bkk-head{display:flex;align-items:flex-end;justify-content:space-between;gap:2rem;margin-bottom:2.4rem}.bkk-eyebrow{display:inline-flex;align-items:center;gap:.55rem;font-size:.7rem;font-weight:900;letter-spacing:.19em;text-transform:uppercase;color:#2f6fa8;margin-bottom:.65rem}.bkk-eyebrow:before{content:"";width:26px;height:2px;background:linear-gradient(90deg,#ffd54a,#ffb300)}.bkk-heading{font-family:var(--font-display);font-size:clamp(2rem,4vw,3.4rem);line-height:1;letter-spacing:-.025em;margin:0;color:#0d3a66}.bkk-heading em{font-style:normal;color:transparent;background:linear-gradient(135deg,#ffd54a,#ff8a00);-webkit-background-clip:text;background-clip:text}.bkk-sub{max-width:600px;margin:.85rem 0 0;color:#52657a;font-size:.92rem;line-height:1.75}.bkk-num{font-family:var(--font-display);font-weight:900;font-size:clamp(4rem,7vw,6.5rem);line-height:1;color:rgba(13,58,102,.06);user-select:none}
.bkk-intro{display:grid;grid-template-columns:1.25fr .75fr;gap:1.4rem}.bkk-card{background:#fff;border:1px solid rgba(13,58,102,.1);border-radius:22px;box-shadow:0 14px 40px rgba(13,58,102,.07);padding:1.7rem}.bkk-card h3{font-family:var(--font-display);font-size:1.25rem;margin:0 0 .65rem;color:#0d3a66}.bkk-card p{font-size:.86rem;line-height:1.8;color:#52657a;margin:0}.bkk-vision{background:#0d3a66;color:#fff}.bkk-vision h3{color:#fff}.bkk-vision p{color:rgba(235,245,253,.82)}.bkk-quote{margin-top:1.1rem;padding:1rem 1.1rem;border-left:3px solid #ffc107;background:rgba(255,255,255,.06);font-size:.86rem;line-height:1.7;color:#fff;font-weight:700}
.bkk-services{display:grid;grid-template-columns:repeat(3,1fr);gap:1.1rem}.bkk-service{background:#fff;border:1px solid rgba(13,58,102,.1);border-radius:18px;padding:1.45rem;box-shadow:0 10px 28px rgba(13,58,102,.06);transition:.3s}.bkk-service:hover{transform:translateY(-5px);box-shadow:0 18px 42px rgba(13,58,102,.13)}.bkk-icon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;background:#eaf2fb;color:#0d3a66;font-size:1rem;margin-bottom:.9rem}.bkk-service:nth-child(3n+2) .bkk-icon{background:#fff6df;color:#c88900}.bkk-service:nth-child(3n+3) .bkk-icon{background:#eef8f2;color:#2b8156}.bkk-service h4{font-family:var(--font-display);font-size:1rem;margin:0 0 .45rem;color:#0d3a66}.bkk-service p{font-size:.78rem;line-height:1.7;color:#65788d;margin:0}
.bkk-jobs{background:#f1f5f9}.bkk-job-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1.15rem}.bkk-job{background:#fff;border:1px solid rgba(13,58,102,.1);border-radius:19px;padding:1.35rem;box-shadow:0 10px 28px rgba(13,58,102,.06);display:flex;flex-direction:column;gap:.75rem}.bkk-job-top{display:flex;align-items:center;justify-content:space-between;gap:.7rem}.bkk-status{display:inline-flex;align-items:center;gap:.4rem;border-radius:999px;padding:.34rem .65rem;font-size:.62rem;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.bkk-status.archive{background:#eef1f4;color:#64778b}.bkk-date{font-size:.68rem;color:#7b8da0;font-weight:700}.bkk-job h3{font-family:var(--font-display);font-size:1.12rem;line-height:1.25;margin:0;color:#0d3a66}.bkk-job p{font-size:.8rem;line-height:1.7;color:#596e83;margin:0}.bkk-job-meta{display:flex;flex-wrap:wrap;gap:.45rem;margin-top:auto}.bkk-tag{padding:.4rem .6rem;border-radius:999px;background:#f7f9fc;border:1px solid rgba(13,58,102,.09);font-size:.64rem;color:#536a80;font-weight:700}.bkk-notice{margin-top:1.2rem;padding:1rem 1.1rem;border-radius:15px;background:#fffaf0;border:1px solid rgba(255,179,0,.25);color:#765d24;font-size:.76rem;line-height:1.65}.bkk-notice i{color:#ffb300;margin-right:.35rem}.bkk-status-key{display:flex;flex-wrap:wrap;gap:.55rem;margin-top:1.3rem}.bkk-key{display:inline-flex;align-items:center;gap:.45rem;padding:.48rem .7rem;border-radius:999px;background:#fff;border:1px solid rgba(13,58,102,.1);font-size:.65rem;font-weight:800;color:#5c7085}.bkk-key b{color:#0d3a66}
.bkk-timeline{display:grid;grid-template-columns:repeat(3,1fr);gap:1.2rem}.bkk-year{background:#fff;border:1px solid rgba(13,58,102,.1);border-radius:20px;padding:1.5rem;box-shadow:0 10px 28px rgba(13,58,102,.06)}.bkk-year-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem}.bkk-year-head h3{font-family:var(--font-display);font-size:1.5rem;margin:0;color:#0d3a66}.bkk-year-head span{font-size:.62rem;font-weight:900;letter-spacing:.12em;color:#b8860b;text-transform:uppercase}.bkk-event{display:grid;grid-template-columns:68px 1fr;gap:.75rem;padding:.75rem 0;border-top:1px solid rgba(13,58,102,.08)}.bkk-event:first-of-type{border-top:0}.bkk-month{font-size:.66rem;font-weight:900;color:#ff8a00;text-transform:uppercase}.bkk-event p{margin:0;font-size:.74rem;line-height:1.55;color:#5e7287}
.bkk-alumni{display:grid;grid-template-columns:1.1fr .9fr;gap:1.3rem}.bkk-alumni-list{display:grid;grid-template-columns:repeat(2,1fr);gap:.75rem}.bkk-person{background:#fff;border:1px solid rgba(13,58,102,.1);border-radius:15px;padding:1rem}.bkk-person strong{display:block;font-family:var(--font-display);font-size:.85rem;color:#0d3a66}.bkk-person span{display:block;margin-top:.3rem;font-size:.68rem;line-height:1.55;color:#708398}.bkk-alumni-note{background:linear-gradient(135deg,#0d3a66,#174d80);border-radius:22px;padding:1.7rem;color:#fff;position:relative;overflow:hidden;display:flex;flex-direction:column;justify-content:flex-end;min-height:340px}.bkk-alumni-note h3{position:relative;z-index:2;font-family:var(--font-display);font-size:1.3rem;margin:0 0 .6rem;text-shadow:0 3px 12px rgba(0,0,0,.65),0 1px 4px rgba(0,0,0,.55)}.bkk-alumni-note p{position:relative;z-index:2;font-size:.8rem;line-height:1.75;color:rgba(255,255,255,.95);margin:0;text-shadow:0 2px 10px rgba(0,0,0,.65),0 1px 3px rgba(0,0,0,.55)}
.bkk-tracer{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.bkk-tracer-card{background:#fff;border:1px solid rgba(13,58,102,.1);border-radius:18px;padding:1.4rem;box-shadow:0 10px 28px rgba(13,58,102,.06)}.bkk-tracer-card i{color:#ffb300;font-size:1rem}.bkk-tracer-card h4{font-family:var(--font-display);margin:.7rem 0 .4rem;font-size:1rem;color:#0d3a66}.bkk-tracer-card p{font-size:.76rem;line-height:1.65;color:#667b90;margin:0}.bkk-source{font-size:.68rem;line-height:1.7;color:#7b8da0;margin-top:1.4rem}
.bkk-cta{padding:0 clamp(1.25rem,5vw,5.5rem) clamp(3.5rem,7vw,5rem)}.bkk-cta-box{max-width:1180px;margin:0 auto;background:#0d3a66;border-radius:27px;padding:clamp(2.5rem,5vw,4rem);color:#fff;text-align:center;box-shadow:0 28px 65px rgba(13,58,102,.22);position:relative;overflow:hidden}.bkk-cta-box h2{font-family:var(--font-display);font-size:clamp(2rem,4vw,3.2rem);line-height:1.05;margin:0}.bkk-cta-box h2 em{font-style:normal;color:#ffd54a}.bkk-cta-box p{max-width:650px;margin:1rem auto 0;font-size:.88rem;line-height:1.8;color:rgba(235,245,253,.78)}
.bkk-photo-row{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-top:1.6rem}.bkk-photo-row img{width:100%;height:190px;object-fit:cover;border-radius:18px;box-shadow:0 12px 30px rgba(13,58,102,.1)}
.bkk-alumni-photo{position:absolute;inset:0;z-index:1;width:100%;height:100%;object-fit:cover;margin:0;border-radius:0;box-shadow:none}
@media(max-width:1000px){.bkk-intro,.bkk-alumni{grid-template-columns:1fr}.bkk-services,.bkk-tracer{grid-template-columns:repeat(2,1fr)}.bkk-timeline{grid-template-columns:1fr}}@media(max-width:720px){.bkk-job-grid,.bkk-alumni-list,.bkk-services,.bkk-tracer{grid-template-columns:1fr}.bkk-head{flex-direction:column;align-items:flex-start}.bkk-num{display:none}.bkk-hero{align-items:flex-start;min-height:0}.bkk-hero-inner{padding-top:4.5rem;padding-bottom:4rem}.bkk-title{font-size:clamp(3.2rem,15vw,4.9rem)}.bkk-strip-inner{flex-wrap:wrap}.bkk-photo-row{grid-template-columns:1fr}}
</style>
@endpush

@section('content')
<div class="bkk-page">
<section class="bkk-hero"><div class="bkk-orn" aria-hidden="true"><span class="bkk-ring"></span><span class="bkk-dots"></span></div><div class="bkk-hero-inner"><div class="bkk-kicker">Pusat Informasi Karier Skaneda</div><h1 class="bkk-title"><span class="navy">BKK &amp;</span><span class="gold">Loker</span></h1><p class="bkk-lead">Bursa Kerja Khusus (BKK) SMK Negeri 2 Mojokerto hadir untuk membantu siswa dan alumni memperoleh informasi, akses, serta pendampingan menuju dunia kerja melalui layanan karier, rekrutmen industri, persiapan kerja, dan hubungan dengan dunia usaha dan dunia industri.</p><div class="bkk-pills"><span class="bkk-pill"><i class="fas fa-briefcase"></i> Informasi Karier</span><span class="bkk-pill"><i class="fas fa-building"></i> Rekrutmen Industri</span><span class="bkk-pill"><i class="fas fa-user-graduate"></i> Siswa &amp; Alumni</span></div></div></section>
<div class="bkk-strip"><div class="bkk-strip-inner"><span class="bkk-strip-label"><i class="fas fa-bolt"></i> BKK Skaneda</span><span class="bkk-strip-text">Informasi lowongan, kegiatan BKK, rekrutmen industri, persiapan karier, dan penelusuran lulusan.</span></div></div>

<section class="bkk-section"><div class="bkk-container"><div class="bkk-head"><div><span class="bkk-eyebrow">Tentang BKK</span><h2 class="bkk-heading">Mengenal <em>BKK Skaneda</em></h2><p class="bkk-sub">BKK merupakan layanan sekolah yang menghubungkan kompetensi siswa dan alumni dengan kebutuhan dunia kerja.</p></div><div class="bkk-num">01</div></div><div class="bkk-intro"><article class="bkk-card"><h3>Bursa Kerja Khusus SMK Negeri 2 Mojokerto</h3><p>BKK membantu siswa dan alumni memperoleh informasi, akses, serta pendampingan menuju dunia kerja. Kegiatannya mencakup pelayanan informasi kerja, penempatan dan penyaluran tenaga kerja, kerja sama dengan dunia kerja/dunia industri, administrasi pencari kerja, bimbingan industri dan jabatan, serta pemantauan perkembangan karier lulusan.</p><p style="margin-top:.8rem">Layanan BKK juga berkembang melalui rekrutmen industri, workshop dan seminar karier, simulasi psikotes, job fair/job matching, kegiatan Alumni Berbagi, penelusuran alumni, dan tracer vokasi.</p></article><article class="bkk-card bkk-vision"><h3>Visi BKK</h3><p>Komitmen BKK dalam memberikan pelayanan karier bagi masyarakat pendidikan.</p><div class="bkk-quote">“Kami siap melayani masyarakat pendidikan dan pembelajaran berbasis budaya Kerja, Disiplin dan Berprestasi.”</div></article></div><div class="bkk-photo-row">
<img src="{{ asset('images/bkk/rekruitment-tongtji.png') }}" alt="Dokumentasi kegiatan BKK 1">
<img src="{{ asset('images/bkk/rekruitment-deabakery.png') }}" alt="Dokumentasi kegiatan BKK 2">
<img src="{{ asset('images/bkk/rekruitment-btpn.png') }}" alt="Dokumentasi kegiatan BKK 3">
</div></div></section>

<section class="bkk-section" style="padding-top:1rem"><div class="bkk-container"><div class="bkk-head"><div><span class="bkk-eyebrow">Layanan Utama</span><h2 class="bkk-heading">Apa yang <em>Dilayani?</em></h2></div><div class="bkk-num">02</div></div><div class="bkk-services">
<article class="bkk-service"><div class="bkk-icon"><i class="fas fa-bullhorn"></i></div><h4>Informasi Lowongan Kerja</h4><p>Menyampaikan peluang kerja dari perusahaan dan industri kepada siswa serta alumni.</p></article>
<article class="bkk-service"><div class="bkk-icon"><i class="fas fa-building"></i></div><h4>Rekrutmen Industri</h4><p>Memfasilitasi perusahaan yang melaksanakan seleksi atau rekrutmen di lingkungan sekolah.</p></article>
<article class="bkk-service"><div class="bkk-icon"><i class="fas fa-graduation-cap"></i></div><h4>Persiapan Karier</h4><p>Workshop, seminar, simulasi psikotes, dan pembekalan untuk meningkatkan kesiapan kerja.</p></article>
<article class="bkk-service"><div class="bkk-icon"><i class="fas fa-comments"></i></div><h4>Alumni Berbagi</h4><p>Menghadirkan alumni untuk berbagi pengalaman kerja, studi, dan perjalanan karier.</p></article>
<article class="bkk-service"><div class="bkk-icon"><i class="fas fa-chart-line"></i></div><h4>Tracer Vokasi</h4><p>Menelusuri kondisi lulusan setelah lulus, termasuk bekerja, studi, wirausaha, dan keselarasan pekerjaan.</p></article>
<article class="bkk-service"><div class="bkk-icon"><i class="fas fa-handshake"></i></div><h4>Hubungan Industri</h4><p>Membangun dan memperluas jejaring dengan dunia usaha, dunia industri, lembaga, dan mitra kerja.</p></article>
</div></div></section>

<section class="bkk-section bkk-jobs"><div class="bkk-container"><div class="bkk-head"><div><span class="bkk-eyebrow">Informasi Rekrutmen</span><h2 class="bkk-heading">Loker &amp; <em>Rekrutmen</em></h2><p class="bkk-sub">Dokumentasi rekrutmen yang tercatat pada arsip BKK dan website sekolah.</p></div><div class="bkk-num">03</div></div><div class="bkk-job-grid">
@php
$jobs = [
 ['PT Surabaya Autocomp Indonesia (SAI)','2022–2023','Rekrutmen Operator Produksi. BKK memfasilitasi seleksi alumni dan masyarakat umum melalui tahapan administrasi, tes, wawancara, dan kesehatan.',['Operator Produksi','Seleksi','Tidak dipungut biaya']],
 ['BTPN Syariah','2022, 2023, 2024, 2026','Terdokumentasi sebagai kegiatan rekrutmen dan sosialisasi BKK. Arsip 2026 mencatat sosialisasi dan rekrutmen pada 20 April 2026.',['Rekrutmen','Sosialisasi']],
 ['PT Pesta Pora Abadi (Mie Gacoan)','2023–2024','Rekrutmen tercatat pada Desember 2023 dan Mei 2024 sebagai bagian dari kegiatan penyaluran kerja melalui BKK.',['Rekrutmen','Dunia Kerja']],
 ['PT Lion Superindo & PT Sumber Alfaria Trijaya Tbk','Januari–Februari 2023','PT Lion Superindo tercatat melakukan rekrutmen melalui online. PT Sumber Alfaria Trijaya Tbk tercatat dalam pengajuan kerja sama rekrutmen.',['Online','Kerja Sama']],
 ['Toko Emas Wahyu Redjo','23 Juli 2025','Rekrutmen Pramuniaga di SMK Negeri 2 Mojokerto. Kegiatan diikuti 131 siswa kelas XII dan difasilitasi bersama BKK sekolah.',['Pramuniaga','Rekrutmen Sekolah']],
 ['Tong Tji','22 Desember 2025','Walk-in Interview di SMKN 2 Mojokerto untuk posisi Server, Cook, dan Barista. Minimal SMA/SMK sederajat; fresh graduate dipersilakan.',['Server','Cook','Barista']],
 ['Dea Bakery','23 Desember 2025','Walk-in Interview pukul 09.00–15.00 WIB di SMKN 2 Kota Mojokerto. Dokumen: CV, pas foto, KTP, KK, dan ijazah/SKL.',['Walk-in Interview','CV','Ijazah/SKL']],
 ['PT Pendekar Bodoh (D\'Cost Seafood)','6 Februari 2026','Program Magang & Part-time bersama BKK SMK Negeri 2 Mojokerto.',['Magang','Part-time']],
 ['Jotun','6 April 2026','Sosialisasi dan rekrutmen kerja yang terdokumentasi pada arsip BKK.',['Sosialisasi','Rekrutmen']],
 ['PT Motasa Indonesia','29 Juli 2026','School Hiring dengan posisi Cooker dan Video Editor, penempatan Mojokerto, Jawa Timur. Arsip mencantumkan proses rekrutmen/seleksi gratis.',['Cooker','Video Editor','Mojokerto']],
 ['XLSMART Career Day','30 Juli 2026','Posisi Direct Sales Agent di Aula SMKN 2 Mojokerto. Arsip mencatat kualifikasi usia 18–45 tahun, minimal SMA/sederajat, siap bekerja di lapangan, memiliki motor dan SIM C, serta bersedia bekerja di bawah pihak ketiga.',['Direct Sales Agent','Career Day','Gratis']],
];
@endphp
@foreach($jobs as $job)
<article class="bkk-job"><div class="bkk-job-top"><span class="bkk-status archive"><i class="fas fa-archive"></i> Arsip</span><span class="bkk-date">{{ $job[1] }}</span></div><h3>{{ $job[0] }}</h3><p>{{ $job[2] }}</p><div class="bkk-job-meta">@foreach($job[3] as $tag)<span class="bkk-tag">{{ $tag }}</span>@endforeach</div></article>
@endforeach
</div><div class="bkk-notice"><i class="fas fa-circle-info"></i> Informasi rekrutmen 2025–2026 pada dokumen merupakan arsip berdasarkan tanggal pelaksanaan yang tersedia. Jangan menampilkannya sebagai lowongan aktif tanpa konfirmasi terbaru dari BKK.</div><div class="bkk-status-key"><span class="bkk-key"><b>OPEN</b> pendaftaran masih berlangsung</span><span class="bkk-key"><b>UPCOMING</b> rekrutmen akan datang</span><span class="bkk-key"><b>SELESAI</b> pendaftaran telah berakhir</span><span class="bkk-key"><b>ARSIP</b> dokumentasi rekrutmen/kegiatan</span></div></div></section>

<section class="bkk-section"><div class="bkk-container"><div class="bkk-head"><div><span class="bkk-eyebrow">Jejak Kegiatan</span><h2 class="bkk-heading">Kegiatan <em>BKK</em></h2><p class="bkk-sub">Rekap kegiatan BKK yang tercatat dalam arsip sekolah dan BKK tahun 2022–2024.</p></div><div class="bkk-num">04</div></div><div class="bkk-timeline">
@php
$years = [
 '2022'=>['Januari'=>'Sinkronisasi Program Kerja BKK dengan Dinas Tenaga Kerja Kota Mojokerto.','Februari'=>'Rekrutmen PT Surabaya Autocomp Indonesia (SAI).','April'=>'Workshop Persiapan Karier dengan narasumber HRD PT SAI.','Mei'=>'RAKOR FBKK JATIM; pembuatan Kartu Kuning AK/I; kunjungan ke UPT BLK Mojokerto.','Juli'=>'Sharing with Alumni untuk Peserta Didik Baru.','Agustus'=>'Virtual Meeting berkaitan dengan Tracer Study dari Direktorat Jenderal Pendidikan Vokasi.','November'=>'Rekrutmen BTPN Syariah.','Desember'=>'Simulasi Psikotes dan Career Course “Navigating Your Career Path”.'],
 '2023'=>['Januari'=>'Pengarahan IM JAPAN; kunjungan ke PT Catur Pilar Sejahtera; Kartu Kuning; Job Fair SMKN 1 Driyorejo; rekrutmen PT Lion Superindo.','Februari'=>'Pengajuan kerja sama rekrutmen PT Sumber Alfaria Trijaya Tbk.','Mei'=>'Penelusuran alumni saat pengambilan SKL dan rekrutmen BTPN Syariah.','September'=>'Penilaian alumni oleh industri melalui Tracer Vokasi.','Oktober'=>'Rekrutmen PT SAI.','Desember'=>'Rekrutmen PT Pesta Pora Abadi (Mie Gacoan).','2023'=>'Simulasi Psikotes dan Seminar Karier Menyambut Masa Depan.'],
 '2024'=>['Januari'=>'Kelas Wirausaha dengan Alumni “Onde-Onde Panas Mojokerto” dan rekrutmen BTPN Syariah.','Februari'=>'Kunjungan Sushi Kun Mojokerto dan kegiatan Motivasi Alumni.','April'=>'BKK mengikuti Job Matching di SMKN 1 Kediri.','Mei'=>'Penelusuran alumni saat pengambilan SKL; pengantaran kerja tenaga kerja honorer ke Polres Mojokerto; rekrutmen PT Pesta Pora Abadi.','September'=>'Pemasyarakatan Hubungan Industrial Tahun 2024 di Disnakertrans Provinsi Jawa Timur.','November'=>'Sharing Praktik Baik; briefing alumni yang akan berangkat kerja; seminar karier dan simulasi psikotes.']
];
@endphp
@foreach($years as $year=>$events)<article class="bkk-year"><div class="bkk-year-head"><h3>{{ $year }}</h3><span>Rekap</span></div>@foreach($events as $month=>$event)<div class="bkk-event"><span class="bkk-month">{{ $month }}</span><p>{{ $event }}</p></div>@endforeach</article>@endforeach
</div></div></section>

<section class="bkk-section" style="padding-top:1rem"><div class="bkk-container"><div class="bkk-head"><div><span class="bkk-eyebrow">Alumni Berbagi</span><h2 class="bkk-heading">Cerita dari <em>Lulusan Skaneda</em></h2><p class="bkk-sub">Narasumber Alumni Berbagi pada MPLS SMKN 2 Mojokerto tahun 2026.</p></div><div class="bkk-num">05</div></div><div class="bkk-alumni"><div class="bkk-alumni-list">
@php $alumni=[['Hazel Zachary Nathan Soedrajat','RS. Kamar Medika • DKV'],['Rovino Ramadhani','PT. Rvintech Digital Indonesia • RPL'],['Mohammad Daffa Irawan','BIDDOKKES POLDA JATIM • Kuliner'],['Zidana Khoiron Alif','LYNN Hotel Mojokerto • PS/LPS'],['M. Dzakaa Irawan','PT. Manna Pertiwi Sejahtera • Kuliner'],['Faisal Fikri','Politeknik Negeri Jember • APHP']]; @endphp
@foreach($alumni as $person)<div class="bkk-person"><strong>{{ $person[0] }}</strong><span>{{ $person[1] }}</span></div>@endforeach
</div><aside class="bkk-alumni-note"><img class="bkk-alumni-photo" src="{{ asset('images/bkk/alumni-berbagi.png') }}" alt="Kegiatan Alumni Berbagi MPLS 2026"><h3>Alumni sebagai sumber inspirasi</h3><p>Kegiatan Alumni Berbagi pada MPLS 2026 dilaksanakan pada 15 Juli 2026. Alumni dari berbagai kompetensi berbagi pengalaman kerja maupun studi kepada peserta didik. Kegiatan ini menjadi bagian dari upaya BKK untuk memperluas wawasan karier siswa.</p></aside></div></div></section>

<section class="bkk-section" style="padding-top:1rem"><div class="bkk-container"><div class="bkk-head"><div><span class="bkk-eyebrow">Tracer Vokasi</span><h2 class="bkk-heading">Menelusuri <em>Perjalanan Lulusan</em></h2><p class="bkk-sub">Tracer Vokasi BKK memantau kondisi lulusan setelah menyelesaikan pendidikan.</p></div><div class="bkk-num">06</div></div><div class="bkk-tracer"><article class="bkk-tracer-card"><i class="fas fa-briefcase"></i><h4>Bekerja</h4><p>Menelusuri lulusan yang telah memasuki dunia kerja dan kesesuaiannya dengan kompetensi.</p></article><article class="bkk-tracer-card"><i class="fas fa-graduation-cap"></i><h4>Melanjutkan Studi</h4><p>Mencatat lulusan yang melanjutkan pendidikan serta perkembangan studi setelah lulus.</p></article><article class="bkk-tracer-card"><i class="fas fa-store"></i><h4>Wirausaha</h4><p>Mendokumentasikan lulusan yang memilih membangun usaha dan mengembangkan kemandirian karier.</p></article></div><p class="bkk-source">Data Tracer Vokasi pada dokumen sumber mencakup lulusan 2023 dan 2024. Angka/diagram asli sebaiknya diperbarui menggunakan arsip administrasi/tracer terbaru BKK sebelum dipublikasikan.</p></div></section>

<section class="bkk-cta"><div class="bkk-cta-box"><h2>Siap melangkah menuju <em>dunia kerja?</em></h2><p>Pantau informasi rekrutmen, kegiatan BKK, pembekalan karier, dan berbagai kesempatan yang dipublikasikan oleh SMK Negeri 2 Mojokerto.</p></div></section>
<section class="bkk-section" style="padding-top:0"><div class="bkk-container"><p class="bkk-source">Sumber informasi: website resmi SMK Negeri 2 Mojokerto dan arsip/dokumentasi BKK yang diberikan. Informasi lowongan harus diverifikasi kembali oleh pengelola BKK sebelum diberi status aktif.</p></div></section>
</div>
@endsection